server: 
  port: 80

config:
  domain: http://test.com  ##本工程域名(用于授权回调,需要公众号配置安全域)
  
account:  ##微信公众号配置
  appid: 
  secret: 
       
appList:  ##业务列表, 每增加一项业务添加对应信息
    test:  #业务key(自定义业务名称,授权时需要客户端传入)
      returnUrl: http://test.com #授权成功后回调地址

logging:
  level:
    org:
      springframework: INFO